### ISSUE TITLE
Parts not moving or resizing

### ISSUE THREAD

**Issue by LegoChronicle** [F3XTeam/ROBLOX-Building-Tools#70]
Some parts or not moving or not resizing in the last update, this is however not the case with all of them. Following errors can be found in the logs:
![bug](https://cloud.githubusercontent.com/assets/11509309/8525795/4212bace-2403-11e5-81a4-0ec8161c0629.PNG)

**Comment by NNickey** [comment]
Your F3X tools seems modified. Did you get the original from the creator GigsD4X.
Original F3X. http://www.roblox.com/Building-Tools-by-F3X-item?id=142785488
Line 696 is a comment. 
	-- Create the main container for notifications
![screenshot_13](https://cloud.githubusercontent.com/assets/3466265/8539037/61d730d0-2433-11e5-9211-65175577f1e1.png)

**Comment by GigsD4X** [comment]
@NNickey Haha, what happens is that each tool script inserts itself into the core script's environment, as you can see this at the top of any tool script. So, since the core script executes them what ends up happening is that the output tells you the correct line, just the _wrong script_.

**Comment by NNickey** [comment]
@GigsD4X I thought if that the inserted script encountered an error, it would at least direct you exactly to which script it errored. For example, 
![screenshot_14](https://cloud.githubusercontent.com/assets/3466265/8539156/fa28355e-2434-11e5-9ad9-9ef949aed326.png)
But in his picture, It looked like his F3X was modified, because it has the final character cut out.
"Building Tools By F3" and that it didn't say anywhere exact like "Building Tools By F3X.BTMoveTool".

**Comment by GigsD4X** [comment]
I think it just trims it out if it's too long :P

**Comment by NNickey** [comment]
Yep. Just found that out.. Shame on you Roblox..

**Comment by LegoChronicle** [comment]
@NNickey My script isn't modified in any way.

**Comment by LegoChronicle** [comment]
Issue had to do with AntiLeak in EISS being enabled. I've disabled this feature and everything seems to be working again. You can close this for me.

**Comment by GigsD4X** [comment]
Alright, great!
